version: '3'
services:
  php:
    build: .
    image: a2way/docker_base-php-fpm-laravel
    env_file:
      - ./env/main.env
  openresty:
    image: a2way/docker_base-openresty-php:v1.1.0
    ports:
      - 8000:80
    environment:
      - PHP_FPM_HOST=php
